### Array is the linear data structure which can have only same datatype element.
### List can have mixed datatype value in it.
- use tab buttom to know functionality of numpy

In [16]:
import numpy as np
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

arr = np.array([list1,list2,list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
arr.shape

(3, 5)

In [19]:
arr= np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [20]:
arr1=arr # is the refernce type, means if we do changes in arr1 then changes will reflect back to arr also
arr1=arr.copy() # use .copy for no change reflections


In [21]:
# one can use conditions in np array as well like
# 
arr[arr<5]

array([0, 2, 4])

In [22]:
## random distribution values lies in 0..1
np.random.rand(4,3)

arr_ex=np.random.randn(3,2)
arr_ex

array([[ 0.73408191,  1.14389256],
       [ 0.18693436, -0.45474336],
       [ 1.14621164, -1.22721113]])

In [23]:
a=np.arange(30).reshape(3,10)
print (a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [24]:
for row in a:
    print(row)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]


In [25]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [26]:
for x in np.nditer(a,order='C'):
    print (x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [27]:
for x in np.nditer(a,order='F'):
    print(x)

0
10
20
1
11
21
2
12
22
3
13
23
4
14
24
5
15
25
6
16
26
7
17
27
8
18
28
9
19
29


In [28]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...]=x*x

In [29]:
print(x)

841


In [30]:
b=np.arange(30).reshape(3,10)

In [31]:
for x,y in np.nditer([a,b]):
    print (x,y)

0 0
1 1
4 2
9 3
16 4
25 5
36 6
49 7
64 8
81 9
100 10
121 11
144 12
169 13
196 14
225 15
256 16
289 17
324 18
361 19
400 20
441 21
484 22
529 23
576 24
625 25
676 26
729 27
784 28
841 29


In [32]:
a=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [33]:
# its a three diensional array
a=np.array([[[1,2,3],[4,5,6]]])
print (a)

[[[1 2 3]
  [4 5 6]]]


In [34]:
# numpy array take less memory ,less time and more compatible
# here is quick demo
import time as t
import numpy as np
size=10000000
a=np.arange(size)
b=np.arange(size)

start=t.time()
result = a+b
print ("time to add to numpy array is :",t.time()-start)

# printing both array together
# for x,y in zip(a,b):
#    print(x,y)

# check for list
a=range(size)
b=range(size)

start=t.time()
result=[(x+y) for x,y in zip(a,b)]
print ("time to add to list array is :",t.time()-start)



# As in the result we can see list is taking way much time than numpy array

time to add to numpy array is : 0.03861403465270996
time to add to list array is : 0.7832739353179932


In [35]:
# in order to prove that numpy array is less memory than list
import sys as sys

a=range(1000)
b=np.arange(1000)

print("memory for list is :",sys.getsizeof(5)*len(a))
print("memory for numpy array is :",b.size*b.itemsize)

# AS we can see in result list is taking way much memory than numpy array thank you


memory for list is : 28000
memory for numpy array is : 8000


In [36]:
a=np.arange(10,dtype=np.float64).reshape(5,2)
print(a)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [37]:
# we can have operation directly on array like
# +,-,*,power and dot product

b=np.arange(10).reshape(2,5)

print (a.dot(b))   # doing dot product

[[  5.   6.   7.   8.   9.]
 [ 15.  20.  25.  30.  35.]
 [ 25.  34.  43.  52.  61.]
 [ 35.  48.  61.  74.  87.]
 [ 45.  62.  79.  96. 113.]]


In [38]:
# slicing and indexing also there in numpy array
# should print last row
print(a[-1])

# should print 2 to 5 row
print(a[2:4])

# should print first two row with both column
print(a[0:2,1])

[8. 9.]
[[4. 5.]
 [6. 7.]]
[1. 3.]
